#!/usr/bin/env bash

command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.  Aborting."; exit 1; }
command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.  Aborting."; exit 1; }

# customisation: 

BOM_PRODUCT="IDQ60901/IDQ60901.94576.json" # Brisbane
APIKEY="b0aa21c8ed417b979ce80f63faf0ad69"
CITY_ID="2174003" # Brisbane, Aus
ALARMING_TEMP=30
ALARMING_WIND=30

# end of customisations

# take temp, wind speed & direction from Bureau of Met. and the rest from openweathermap.org:
BOM_URL="http://reg.bom.gov.au/fwo/$BOM_PRODUCT"
BOM_WEATHER=$( wget -qO- "$BOM_URL" )
WEATHER_TEMP=$( echo "$BOM_WEATHER" | jq '.observations.data[0].air_temp' )
WIND_SPEED=$( echo "$BOM_WEATHER" | jq '.observations.data[0].wind_spd_kmh' )
WIND_DIR=$( echo "$BOM_WEATHER" | jq '.observations.data[0].wind_dir' )

URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=metric&APPID=${APIKEY}"

WEATHER_RESPONSE=$(wget -qO- "${URL}")

WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
SUNRISE=$( echo "$WEATHER_RESPONSE" | jq '.sys.sunrise' )
SUNSET=$( echo "$WEATHER_RESPONSE" | jq '.sys.sunset' )

case $WEATHER_CONDITION in
  'Clouds')
    WEATHER_ICON="Cloud"
    ;;
  'Rain')
    WEATHER_ICON="Rain"
    ;;
  'Snow')
    WEATHER_ICON="Snow"
    ;;
  *)
    WEATHER_ICON="Nothing"
    ;;
esac

SUNRISE="Sunrise - $( date -d @$SUNRISE '+%H:%M')"
SUNSET="Sunset - $( date -d @$SUNSET '+%H:%M')"
echo "${WEATHER_ICON} ${WEATHER_TEMP}°C ${WIND_SPEED}kph ${WIND_DIR} $SUNRISE $SUNSET"
echo "${WEATHER_ICON} ${WEATHER_TEMP}°C ${WIND_SPEED}kph ${WIND_DIR} $SUNRISE $SUNSET"

awk "BEGIN { if ( $WEATHER_TEMP > $ALARMING_TEMP || $WIND_SPEED > $ALARMING_WIND ) { print \"#FF0000\" } }"
